### ISSUE TITLE
Colors of the visualizations not displayed correctly

### ISSUE THREAD

**Issue by sduenas** [bitergia-analytics/bitergia-analytics#28]
This is an error related to OpenSearch Dashboards >= 2.10.

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5422

--------

- [x] Technical Review
- [X] Business Review
- [x] Upstream Merge

**Comment by evamillan** [comment]
PR upstream: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7051

**Comment by dicortazar** [comment]
Work done :).
