### ISSUE TITLE
Read only access to SortingHat's API

### ISSUE THREAD

**Issue by fioddor** [bitergia-analytics/bitergia-analytics#48]
With the current profiles, access to SortingHat's API is either fully granted or reserved.

It should be possible to have users accessing it in read-only mode (without permission to execute mutations).

--------

- [x] Technical Review
- [x] Business Review

**Comment by canasdiaz** [comment]
@dicortazar Is this something that you want to be part of the current product?

**Comment by canasdiaz** [comment]
@evamillan when do you plan this to be ready for review?

**Comment by evamillan** [comment]
> @evamillan when do you plan this to be ready for review?

Today or tomorrow for code review.

**Comment by evamillan** [comment]
PR: https://github.com/chaoss/grimoirelab-sortinghat/pull/897

**Comment by dicortazar** [comment]
Work done.
