### ISSUE TITLE
Add missing fields to Kitsune/Sumo index

### ISSUE THREAD

**Issue by canasdiaz** [bitergia-analytics/bitergia-analytics#52]
Please apply the following modifications to the Kitsune enriched index:
 * https://github.com/chaoss/grimoirelab-elk/issues/1144
 * https://github.com/chaoss/grimoirelab-elk/issues/1145
 * https://github.com/chaoss/grimoirelab-elk/issues/1146
 * https://github.com/chaoss/grimoirelab-elk/issues/1147

Steps:
 * Create the code.
 * Send a head-up to the Bitergia production team to deploy the new release.

**Comment by canasdiaz** [comment]
There is a PR by @jjmerchante that may solve this ticket https://github.com/chaoss/grimoirelab-elk/pull/1148

**Comment by canasdiaz** [comment]
@jjmerchante @sduenas do you know when this will be deployed in production?

**Comment by canasdiaz** [comment]
@sduenas Please provide an ETA.

**Comment by sduenas** [comment]
Not sure when. We need to create a release, but we also need a new release of GrilmoireLab. Don't expect before May 6.

**Comment by canasdiaz** [comment]
@jjmerchante Do you have an answer for this?

**Comment by canasdiaz** [comment]
This is working in production. We are done here.
