### ISSUE TITLE
Unify jobs are not complete enough for merging by email and author name

### ISSUE THREAD

**Issue by canasdiaz** [bitergia-analytics/bitergia-analytics#59]
The identities manager is not allowing our team to unify accounts using two conditions that are needed to have good quality in the identities dataset. The conditions are:

* same email in any data source
* same username in the same data source (the typical example here is GitHub with the many APIs it has)

With the current version in production, the only way to do this would be to schedule two different "unify" jobs, but this is not possible either.

Please evaluate and execute the best solution to allow the maintainer of the identity data set to merge identities with the conditions explained above.

**Comment by canasdiaz** [comment]
@sduenas proposed a solution at https://github.com/chaoss/grimoirelab-sortinghat/issues/875

@sduenas please explain how this solution will solve this issue

**Comment by sduenas** [comment]
My proposal is that the flag only applies to match `username` values from the same datasource. Also, these flag only applies to trusted datasources (i.e. github and gitlab). This option can be used with other values to match. So in your case, with just one recommendation job, you will match email that are equal or usernames that are equal and come from github or gitlab.

**Comment by fioddor** [comment]
I believe we can close this ticket.

**Comment by dicortazar** [comment]
Ticket done :).
