### ISSUE TITLE
SortingHat: Link to GitHub Profile

### ISSUE THREAD

**Issue by GeorgLink** [bitergia-analytics/bitergia-analytics#70]
I want to click from SortingHat directly to a contributor's GitHub profile to learn more about them.

A good place for this would be on the individual page in the Profile section.

--------

- [x] Technical Review
- [x] Business Review

**Comment by canasdiaz** [comment]
I also think this will make us more efficient when editing profiles. :+1:

**Comment by evamillan** [comment]
PR: https://github.com/chaoss/grimoirelab-sortinghat/pull/898

**Comment by GeorgLink** [comment]
Yay!

**Comment by dicortazar** [comment]
This looks good from a business perspective. Thanks!

**Comment by dicortazar** [comment]
We can close this ticket.
