### ISSUE TITLE
Duplicated GitHub links in individual's profile

### ISSUE THREAD

**Issue by sduenas** [bitergia-analytics/bitergia-analytics#85]
If an individual has several GitHub identities with the same username, the link to the profile appears duplicated. It should only show the link once for each GitHub profile.

See https://github.com/chaoss/grimoirelab-sortinghat/issues/912 for more info.

**Comment by evamillan** [comment]
PR: https://github.com/chaoss/grimoirelab-sortinghat/pull/914

**Comment by sduenas** [comment]
Fixed upstream.
