### ISSUE TITLE
Git Top projects table not working properly

### ISSUE THREAD

**Issue by Ruth-ikegah** [bitergia-analytics/bitergia-analytics#9]
The Git Top projects table does not filter properly after sorting the table by ascending order. It maintains a static order when you filter the projects.

Bug opened upstream: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4836

**Comment by sduenas** [comment]
Bug opened upstream: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4836

**Comment by sduenas** [comment]
Fixed on 0.15.0.
